import dotenv from "dotenv";
import { PrismaNeon } from "@prisma/adapter-neon";

import { PrismaClient } from "../src/__generated/prisma/client";

dotenv.config({ path: ".env.local" });

const connectionString = `${process.env.DATABASE_URL}`;

const adapter = new PrismaNeon({ connectionString });
const prisma = new PrismaClient({ adapter });

async function main() {
    const tag = await prisma.tag.upsert({
        where: { tag: "ai" },
        update: {},
        create: { tag: "ai" },
    });

    const link = await prisma.link.upsert({
        where: {
            slackMessageTs_url: {
                slackMessageTs: "1719955200.000100",
                url: "https://example.com/articles/vector-databases",
            },
        },
        update: {},
        create: {
            sharedAt: new Date(),
            slackMessageTs: "1719955200.000100",
            slackChannelId: "C0123456789",
            sharedBySlackUserId: "U0456789123",
            sharedByDisplayName: "Sample Curator",
            headline: "Vector Databases for Realtime AI",
            summary:
                "Deep-dive explainer on how vector databases power realtime retrieval-augmented generation workflows.",
            url: "https://example.com/articles/vector-databases",
        },
    });

    await prisma.linkTag.upsert({
        where: {
            linkId_tagId: {
                linkId: link.id,
                tagId: tag.id,
            },
        },
        update: {},
        create: {
            linkId: link.id,
            tagId: tag.id,
        },
    });

    const newsletter = await prisma.newsletter.upsert({
        where: { month: "2025-01" },
        update: {},
        create: {
            month: "2025-01",
            subject: "Byte Keeper · January 2025 Highlights",
            introductionText:
                "January 2025\n\nAutomated draft generated by Byte Keeper workflows.",
        },
    });

    await prisma.newsletterLink.upsert({
        where: {
            newsletterId_linkId: {
                newsletterId: newsletter.id,
                linkId: link.id,
            },
        },
        update: {},
        create: {
            newsletterId: newsletter.id,
            linkId: link.id,
            position: 1,
        },
    });

    console.info("Seed data created (newsletter, link, tag).");
}

main()
    .catch((error) => {
        console.error("Failed to seed database", error);
        process.exitCode = 1;
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
