
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `NewsletterLink` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model NewsletterLink
 * 
 */
export type NewsletterLinkModel = runtime.Types.Result.DefaultSelection<Prisma.$NewsletterLinkPayload>

export type AggregateNewsletterLink = {
  _count: NewsletterLinkCountAggregateOutputType | null
  _avg: NewsletterLinkAvgAggregateOutputType | null
  _sum: NewsletterLinkSumAggregateOutputType | null
  _min: NewsletterLinkMinAggregateOutputType | null
  _max: NewsletterLinkMaxAggregateOutputType | null
}

export type NewsletterLinkAvgAggregateOutputType = {
  position: number | null
}

export type NewsletterLinkSumAggregateOutputType = {
  position: number | null
}

export type NewsletterLinkMinAggregateOutputType = {
  newsletterId: string | null
  linkId: string | null
  position: number | null
}

export type NewsletterLinkMaxAggregateOutputType = {
  newsletterId: string | null
  linkId: string | null
  position: number | null
}

export type NewsletterLinkCountAggregateOutputType = {
  newsletterId: number
  linkId: number
  position: number
  _all: number
}


export type NewsletterLinkAvgAggregateInputType = {
  position?: true
}

export type NewsletterLinkSumAggregateInputType = {
  position?: true
}

export type NewsletterLinkMinAggregateInputType = {
  newsletterId?: true
  linkId?: true
  position?: true
}

export type NewsletterLinkMaxAggregateInputType = {
  newsletterId?: true
  linkId?: true
  position?: true
}

export type NewsletterLinkCountAggregateInputType = {
  newsletterId?: true
  linkId?: true
  position?: true
  _all?: true
}

export type NewsletterLinkAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NewsletterLink to aggregate.
   */
  where?: Prisma.NewsletterLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewsletterLinks to fetch.
   */
  orderBy?: Prisma.NewsletterLinkOrderByWithRelationInput | Prisma.NewsletterLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NewsletterLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewsletterLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewsletterLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned NewsletterLinks
  **/
  _count?: true | NewsletterLinkCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: NewsletterLinkAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: NewsletterLinkSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NewsletterLinkMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NewsletterLinkMaxAggregateInputType
}

export type GetNewsletterLinkAggregateType<T extends NewsletterLinkAggregateArgs> = {
      [P in keyof T & keyof AggregateNewsletterLink]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNewsletterLink[P]>
    : Prisma.GetScalarType<T[P], AggregateNewsletterLink[P]>
}




export type NewsletterLinkGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NewsletterLinkWhereInput
  orderBy?: Prisma.NewsletterLinkOrderByWithAggregationInput | Prisma.NewsletterLinkOrderByWithAggregationInput[]
  by: Prisma.NewsletterLinkScalarFieldEnum[] | Prisma.NewsletterLinkScalarFieldEnum
  having?: Prisma.NewsletterLinkScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NewsletterLinkCountAggregateInputType | true
  _avg?: NewsletterLinkAvgAggregateInputType
  _sum?: NewsletterLinkSumAggregateInputType
  _min?: NewsletterLinkMinAggregateInputType
  _max?: NewsletterLinkMaxAggregateInputType
}

export type NewsletterLinkGroupByOutputType = {
  newsletterId: string
  linkId: string
  position: number
  _count: NewsletterLinkCountAggregateOutputType | null
  _avg: NewsletterLinkAvgAggregateOutputType | null
  _sum: NewsletterLinkSumAggregateOutputType | null
  _min: NewsletterLinkMinAggregateOutputType | null
  _max: NewsletterLinkMaxAggregateOutputType | null
}

type GetNewsletterLinkGroupByPayload<T extends NewsletterLinkGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NewsletterLinkGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NewsletterLinkGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NewsletterLinkGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NewsletterLinkGroupByOutputType[P]>
      }
    >
  >



export type NewsletterLinkWhereInput = {
  AND?: Prisma.NewsletterLinkWhereInput | Prisma.NewsletterLinkWhereInput[]
  OR?: Prisma.NewsletterLinkWhereInput[]
  NOT?: Prisma.NewsletterLinkWhereInput | Prisma.NewsletterLinkWhereInput[]
  newsletterId?: Prisma.StringFilter<"NewsletterLink"> | string
  linkId?: Prisma.StringFilter<"NewsletterLink"> | string
  position?: Prisma.IntFilter<"NewsletterLink"> | number
  newsletter?: Prisma.XOR<Prisma.NewsletterScalarRelationFilter, Prisma.NewsletterWhereInput>
  link?: Prisma.XOR<Prisma.LinkScalarRelationFilter, Prisma.LinkWhereInput>
}

export type NewsletterLinkOrderByWithRelationInput = {
  newsletterId?: Prisma.SortOrder
  linkId?: Prisma.SortOrder
  position?: Prisma.SortOrder
  newsletter?: Prisma.NewsletterOrderByWithRelationInput
  link?: Prisma.LinkOrderByWithRelationInput
}

export type NewsletterLinkWhereUniqueInput = Prisma.AtLeast<{
  newsletterId_linkId?: Prisma.NewsletterLinkNewsletterIdLinkIdCompoundUniqueInput
  AND?: Prisma.NewsletterLinkWhereInput | Prisma.NewsletterLinkWhereInput[]
  OR?: Prisma.NewsletterLinkWhereInput[]
  NOT?: Prisma.NewsletterLinkWhereInput | Prisma.NewsletterLinkWhereInput[]
  newsletterId?: Prisma.StringFilter<"NewsletterLink"> | string
  linkId?: Prisma.StringFilter<"NewsletterLink"> | string
  position?: Prisma.IntFilter<"NewsletterLink"> | number
  newsletter?: Prisma.XOR<Prisma.NewsletterScalarRelationFilter, Prisma.NewsletterWhereInput>
  link?: Prisma.XOR<Prisma.LinkScalarRelationFilter, Prisma.LinkWhereInput>
}, "newsletterId_linkId">

export type NewsletterLinkOrderByWithAggregationInput = {
  newsletterId?: Prisma.SortOrder
  linkId?: Prisma.SortOrder
  position?: Prisma.SortOrder
  _count?: Prisma.NewsletterLinkCountOrderByAggregateInput
  _avg?: Prisma.NewsletterLinkAvgOrderByAggregateInput
  _max?: Prisma.NewsletterLinkMaxOrderByAggregateInput
  _min?: Prisma.NewsletterLinkMinOrderByAggregateInput
  _sum?: Prisma.NewsletterLinkSumOrderByAggregateInput
}

export type NewsletterLinkScalarWhereWithAggregatesInput = {
  AND?: Prisma.NewsletterLinkScalarWhereWithAggregatesInput | Prisma.NewsletterLinkScalarWhereWithAggregatesInput[]
  OR?: Prisma.NewsletterLinkScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NewsletterLinkScalarWhereWithAggregatesInput | Prisma.NewsletterLinkScalarWhereWithAggregatesInput[]
  newsletterId?: Prisma.StringWithAggregatesFilter<"NewsletterLink"> | string
  linkId?: Prisma.StringWithAggregatesFilter<"NewsletterLink"> | string
  position?: Prisma.IntWithAggregatesFilter<"NewsletterLink"> | number
}

export type NewsletterLinkCreateInput = {
  position?: number
  newsletter: Prisma.NewsletterCreateNestedOneWithoutLinksInput
  link: Prisma.LinkCreateNestedOneWithoutNewslettersInput
}

export type NewsletterLinkUncheckedCreateInput = {
  newsletterId: string
  linkId: string
  position?: number
}

export type NewsletterLinkUpdateInput = {
  position?: Prisma.IntFieldUpdateOperationsInput | number
  newsletter?: Prisma.NewsletterUpdateOneRequiredWithoutLinksNestedInput
  link?: Prisma.LinkUpdateOneRequiredWithoutNewslettersNestedInput
}

export type NewsletterLinkUncheckedUpdateInput = {
  newsletterId?: Prisma.StringFieldUpdateOperationsInput | string
  linkId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type NewsletterLinkCreateManyInput = {
  newsletterId: string
  linkId: string
  position?: number
}

export type NewsletterLinkUpdateManyMutationInput = {
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type NewsletterLinkUncheckedUpdateManyInput = {
  newsletterId?: Prisma.StringFieldUpdateOperationsInput | string
  linkId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type NewsletterLinkListRelationFilter = {
  every?: Prisma.NewsletterLinkWhereInput
  some?: Prisma.NewsletterLinkWhereInput
  none?: Prisma.NewsletterLinkWhereInput
}

export type NewsletterLinkOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NewsletterLinkNewsletterIdLinkIdCompoundUniqueInput = {
  newsletterId: string
  linkId: string
}

export type NewsletterLinkCountOrderByAggregateInput = {
  newsletterId?: Prisma.SortOrder
  linkId?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type NewsletterLinkAvgOrderByAggregateInput = {
  position?: Prisma.SortOrder
}

export type NewsletterLinkMaxOrderByAggregateInput = {
  newsletterId?: Prisma.SortOrder
  linkId?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type NewsletterLinkMinOrderByAggregateInput = {
  newsletterId?: Prisma.SortOrder
  linkId?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type NewsletterLinkSumOrderByAggregateInput = {
  position?: Prisma.SortOrder
}

export type NewsletterLinkCreateNestedManyWithoutLinkInput = {
  create?: Prisma.XOR<Prisma.NewsletterLinkCreateWithoutLinkInput, Prisma.NewsletterLinkUncheckedCreateWithoutLinkInput> | Prisma.NewsletterLinkCreateWithoutLinkInput[] | Prisma.NewsletterLinkUncheckedCreateWithoutLinkInput[]
  connectOrCreate?: Prisma.NewsletterLinkCreateOrConnectWithoutLinkInput | Prisma.NewsletterLinkCreateOrConnectWithoutLinkInput[]
  createMany?: Prisma.NewsletterLinkCreateManyLinkInputEnvelope
  connect?: Prisma.NewsletterLinkWhereUniqueInput | Prisma.NewsletterLinkWhereUniqueInput[]
}

export type NewsletterLinkUncheckedCreateNestedManyWithoutLinkInput = {
  create?: Prisma.XOR<Prisma.NewsletterLinkCreateWithoutLinkInput, Prisma.NewsletterLinkUncheckedCreateWithoutLinkInput> | Prisma.NewsletterLinkCreateWithoutLinkInput[] | Prisma.NewsletterLinkUncheckedCreateWithoutLinkInput[]
  connectOrCreate?: Prisma.NewsletterLinkCreateOrConnectWithoutLinkInput | Prisma.NewsletterLinkCreateOrConnectWithoutLinkInput[]
  createMany?: Prisma.NewsletterLinkCreateManyLinkInputEnvelope
  connect?: Prisma.NewsletterLinkWhereUniqueInput | Prisma.NewsletterLinkWhereUniqueInput[]
}

export type NewsletterLinkUpdateManyWithoutLinkNestedInput = {
  create?: Prisma.XOR<Prisma.NewsletterLinkCreateWithoutLinkInput, Prisma.NewsletterLinkUncheckedCreateWithoutLinkInput> | Prisma.NewsletterLinkCreateWithoutLinkInput[] | Prisma.NewsletterLinkUncheckedCreateWithoutLinkInput[]
  connectOrCreate?: Prisma.NewsletterLinkCreateOrConnectWithoutLinkInput | Prisma.NewsletterLinkCreateOrConnectWithoutLinkInput[]
  upsert?: Prisma.NewsletterLinkUpsertWithWhereUniqueWithoutLinkInput | Prisma.NewsletterLinkUpsertWithWhereUniqueWithoutLinkInput[]
  createMany?: Prisma.NewsletterLinkCreateManyLinkInputEnvelope
  set?: Prisma.NewsletterLinkWhereUniqueInput | Prisma.NewsletterLinkWhereUniqueInput[]
  disconnect?: Prisma.NewsletterLinkWhereUniqueInput | Prisma.NewsletterLinkWhereUniqueInput[]
  delete?: Prisma.NewsletterLinkWhereUniqueInput | Prisma.NewsletterLinkWhereUniqueInput[]
  connect?: Prisma.NewsletterLinkWhereUniqueInput | Prisma.NewsletterLinkWhereUniqueInput[]
  update?: Prisma.NewsletterLinkUpdateWithWhereUniqueWithoutLinkInput | Prisma.NewsletterLinkUpdateWithWhereUniqueWithoutLinkInput[]
  updateMany?: Prisma.NewsletterLinkUpdateManyWithWhereWithoutLinkInput | Prisma.NewsletterLinkUpdateManyWithWhereWithoutLinkInput[]
  deleteMany?: Prisma.NewsletterLinkScalarWhereInput | Prisma.NewsletterLinkScalarWhereInput[]
}

export type NewsletterLinkUncheckedUpdateManyWithoutLinkNestedInput = {
  create?: Prisma.XOR<Prisma.NewsletterLinkCreateWithoutLinkInput, Prisma.NewsletterLinkUncheckedCreateWithoutLinkInput> | Prisma.NewsletterLinkCreateWithoutLinkInput[] | Prisma.NewsletterLinkUncheckedCreateWithoutLinkInput[]
  connectOrCreate?: Prisma.NewsletterLinkCreateOrConnectWithoutLinkInput | Prisma.NewsletterLinkCreateOrConnectWithoutLinkInput[]
  upsert?: Prisma.NewsletterLinkUpsertWithWhereUniqueWithoutLinkInput | Prisma.NewsletterLinkUpsertWithWhereUniqueWithoutLinkInput[]
  createMany?: Prisma.NewsletterLinkCreateManyLinkInputEnvelope
  set?: Prisma.NewsletterLinkWhereUniqueInput | Prisma.NewsletterLinkWhereUniqueInput[]
  disconnect?: Prisma.NewsletterLinkWhereUniqueInput | Prisma.NewsletterLinkWhereUniqueInput[]
  delete?: Prisma.NewsletterLinkWhereUniqueInput | Prisma.NewsletterLinkWhereUniqueInput[]
  connect?: Prisma.NewsletterLinkWhereUniqueInput | Prisma.NewsletterLinkWhereUniqueInput[]
  update?: Prisma.NewsletterLinkUpdateWithWhereUniqueWithoutLinkInput | Prisma.NewsletterLinkUpdateWithWhereUniqueWithoutLinkInput[]
  updateMany?: Prisma.NewsletterLinkUpdateManyWithWhereWithoutLinkInput | Prisma.NewsletterLinkUpdateManyWithWhereWithoutLinkInput[]
  deleteMany?: Prisma.NewsletterLinkScalarWhereInput | Prisma.NewsletterLinkScalarWhereInput[]
}

export type NewsletterLinkCreateNestedManyWithoutNewsletterInput = {
  create?: Prisma.XOR<Prisma.NewsletterLinkCreateWithoutNewsletterInput, Prisma.NewsletterLinkUncheckedCreateWithoutNewsletterInput> | Prisma.NewsletterLinkCreateWithoutNewsletterInput[] | Prisma.NewsletterLinkUncheckedCreateWithoutNewsletterInput[]
  connectOrCreate?: Prisma.NewsletterLinkCreateOrConnectWithoutNewsletterInput | Prisma.NewsletterLinkCreateOrConnectWithoutNewsletterInput[]
  createMany?: Prisma.NewsletterLinkCreateManyNewsletterInputEnvelope
  connect?: Prisma.NewsletterLinkWhereUniqueInput | Prisma.NewsletterLinkWhereUniqueInput[]
}

export type NewsletterLinkUncheckedCreateNestedManyWithoutNewsletterInput = {
  create?: Prisma.XOR<Prisma.NewsletterLinkCreateWithoutNewsletterInput, Prisma.NewsletterLinkUncheckedCreateWithoutNewsletterInput> | Prisma.NewsletterLinkCreateWithoutNewsletterInput[] | Prisma.NewsletterLinkUncheckedCreateWithoutNewsletterInput[]
  connectOrCreate?: Prisma.NewsletterLinkCreateOrConnectWithoutNewsletterInput | Prisma.NewsletterLinkCreateOrConnectWithoutNewsletterInput[]
  createMany?: Prisma.NewsletterLinkCreateManyNewsletterInputEnvelope
  connect?: Prisma.NewsletterLinkWhereUniqueInput | Prisma.NewsletterLinkWhereUniqueInput[]
}

export type NewsletterLinkUpdateManyWithoutNewsletterNestedInput = {
  create?: Prisma.XOR<Prisma.NewsletterLinkCreateWithoutNewsletterInput, Prisma.NewsletterLinkUncheckedCreateWithoutNewsletterInput> | Prisma.NewsletterLinkCreateWithoutNewsletterInput[] | Prisma.NewsletterLinkUncheckedCreateWithoutNewsletterInput[]
  connectOrCreate?: Prisma.NewsletterLinkCreateOrConnectWithoutNewsletterInput | Prisma.NewsletterLinkCreateOrConnectWithoutNewsletterInput[]
  upsert?: Prisma.NewsletterLinkUpsertWithWhereUniqueWithoutNewsletterInput | Prisma.NewsletterLinkUpsertWithWhereUniqueWithoutNewsletterInput[]
  createMany?: Prisma.NewsletterLinkCreateManyNewsletterInputEnvelope
  set?: Prisma.NewsletterLinkWhereUniqueInput | Prisma.NewsletterLinkWhereUniqueInput[]
  disconnect?: Prisma.NewsletterLinkWhereUniqueInput | Prisma.NewsletterLinkWhereUniqueInput[]
  delete?: Prisma.NewsletterLinkWhereUniqueInput | Prisma.NewsletterLinkWhereUniqueInput[]
  connect?: Prisma.NewsletterLinkWhereUniqueInput | Prisma.NewsletterLinkWhereUniqueInput[]
  update?: Prisma.NewsletterLinkUpdateWithWhereUniqueWithoutNewsletterInput | Prisma.NewsletterLinkUpdateWithWhereUniqueWithoutNewsletterInput[]
  updateMany?: Prisma.NewsletterLinkUpdateManyWithWhereWithoutNewsletterInput | Prisma.NewsletterLinkUpdateManyWithWhereWithoutNewsletterInput[]
  deleteMany?: Prisma.NewsletterLinkScalarWhereInput | Prisma.NewsletterLinkScalarWhereInput[]
}

export type NewsletterLinkUncheckedUpdateManyWithoutNewsletterNestedInput = {
  create?: Prisma.XOR<Prisma.NewsletterLinkCreateWithoutNewsletterInput, Prisma.NewsletterLinkUncheckedCreateWithoutNewsletterInput> | Prisma.NewsletterLinkCreateWithoutNewsletterInput[] | Prisma.NewsletterLinkUncheckedCreateWithoutNewsletterInput[]
  connectOrCreate?: Prisma.NewsletterLinkCreateOrConnectWithoutNewsletterInput | Prisma.NewsletterLinkCreateOrConnectWithoutNewsletterInput[]
  upsert?: Prisma.NewsletterLinkUpsertWithWhereUniqueWithoutNewsletterInput | Prisma.NewsletterLinkUpsertWithWhereUniqueWithoutNewsletterInput[]
  createMany?: Prisma.NewsletterLinkCreateManyNewsletterInputEnvelope
  set?: Prisma.NewsletterLinkWhereUniqueInput | Prisma.NewsletterLinkWhereUniqueInput[]
  disconnect?: Prisma.NewsletterLinkWhereUniqueInput | Prisma.NewsletterLinkWhereUniqueInput[]
  delete?: Prisma.NewsletterLinkWhereUniqueInput | Prisma.NewsletterLinkWhereUniqueInput[]
  connect?: Prisma.NewsletterLinkWhereUniqueInput | Prisma.NewsletterLinkWhereUniqueInput[]
  update?: Prisma.NewsletterLinkUpdateWithWhereUniqueWithoutNewsletterInput | Prisma.NewsletterLinkUpdateWithWhereUniqueWithoutNewsletterInput[]
  updateMany?: Prisma.NewsletterLinkUpdateManyWithWhereWithoutNewsletterInput | Prisma.NewsletterLinkUpdateManyWithWhereWithoutNewsletterInput[]
  deleteMany?: Prisma.NewsletterLinkScalarWhereInput | Prisma.NewsletterLinkScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NewsletterLinkCreateWithoutLinkInput = {
  position?: number
  newsletter: Prisma.NewsletterCreateNestedOneWithoutLinksInput
}

export type NewsletterLinkUncheckedCreateWithoutLinkInput = {
  newsletterId: string
  position?: number
}

export type NewsletterLinkCreateOrConnectWithoutLinkInput = {
  where: Prisma.NewsletterLinkWhereUniqueInput
  create: Prisma.XOR<Prisma.NewsletterLinkCreateWithoutLinkInput, Prisma.NewsletterLinkUncheckedCreateWithoutLinkInput>
}

export type NewsletterLinkCreateManyLinkInputEnvelope = {
  data: Prisma.NewsletterLinkCreateManyLinkInput | Prisma.NewsletterLinkCreateManyLinkInput[]
  skipDuplicates?: boolean
}

export type NewsletterLinkUpsertWithWhereUniqueWithoutLinkInput = {
  where: Prisma.NewsletterLinkWhereUniqueInput
  update: Prisma.XOR<Prisma.NewsletterLinkUpdateWithoutLinkInput, Prisma.NewsletterLinkUncheckedUpdateWithoutLinkInput>
  create: Prisma.XOR<Prisma.NewsletterLinkCreateWithoutLinkInput, Prisma.NewsletterLinkUncheckedCreateWithoutLinkInput>
}

export type NewsletterLinkUpdateWithWhereUniqueWithoutLinkInput = {
  where: Prisma.NewsletterLinkWhereUniqueInput
  data: Prisma.XOR<Prisma.NewsletterLinkUpdateWithoutLinkInput, Prisma.NewsletterLinkUncheckedUpdateWithoutLinkInput>
}

export type NewsletterLinkUpdateManyWithWhereWithoutLinkInput = {
  where: Prisma.NewsletterLinkScalarWhereInput
  data: Prisma.XOR<Prisma.NewsletterLinkUpdateManyMutationInput, Prisma.NewsletterLinkUncheckedUpdateManyWithoutLinkInput>
}

export type NewsletterLinkScalarWhereInput = {
  AND?: Prisma.NewsletterLinkScalarWhereInput | Prisma.NewsletterLinkScalarWhereInput[]
  OR?: Prisma.NewsletterLinkScalarWhereInput[]
  NOT?: Prisma.NewsletterLinkScalarWhereInput | Prisma.NewsletterLinkScalarWhereInput[]
  newsletterId?: Prisma.StringFilter<"NewsletterLink"> | string
  linkId?: Prisma.StringFilter<"NewsletterLink"> | string
  position?: Prisma.IntFilter<"NewsletterLink"> | number
}

export type NewsletterLinkCreateWithoutNewsletterInput = {
  position?: number
  link: Prisma.LinkCreateNestedOneWithoutNewslettersInput
}

export type NewsletterLinkUncheckedCreateWithoutNewsletterInput = {
  linkId: string
  position?: number
}

export type NewsletterLinkCreateOrConnectWithoutNewsletterInput = {
  where: Prisma.NewsletterLinkWhereUniqueInput
  create: Prisma.XOR<Prisma.NewsletterLinkCreateWithoutNewsletterInput, Prisma.NewsletterLinkUncheckedCreateWithoutNewsletterInput>
}

export type NewsletterLinkCreateManyNewsletterInputEnvelope = {
  data: Prisma.NewsletterLinkCreateManyNewsletterInput | Prisma.NewsletterLinkCreateManyNewsletterInput[]
  skipDuplicates?: boolean
}

export type NewsletterLinkUpsertWithWhereUniqueWithoutNewsletterInput = {
  where: Prisma.NewsletterLinkWhereUniqueInput
  update: Prisma.XOR<Prisma.NewsletterLinkUpdateWithoutNewsletterInput, Prisma.NewsletterLinkUncheckedUpdateWithoutNewsletterInput>
  create: Prisma.XOR<Prisma.NewsletterLinkCreateWithoutNewsletterInput, Prisma.NewsletterLinkUncheckedCreateWithoutNewsletterInput>
}

export type NewsletterLinkUpdateWithWhereUniqueWithoutNewsletterInput = {
  where: Prisma.NewsletterLinkWhereUniqueInput
  data: Prisma.XOR<Prisma.NewsletterLinkUpdateWithoutNewsletterInput, Prisma.NewsletterLinkUncheckedUpdateWithoutNewsletterInput>
}

export type NewsletterLinkUpdateManyWithWhereWithoutNewsletterInput = {
  where: Prisma.NewsletterLinkScalarWhereInput
  data: Prisma.XOR<Prisma.NewsletterLinkUpdateManyMutationInput, Prisma.NewsletterLinkUncheckedUpdateManyWithoutNewsletterInput>
}

export type NewsletterLinkCreateManyLinkInput = {
  newsletterId: string
  position?: number
}

export type NewsletterLinkUpdateWithoutLinkInput = {
  position?: Prisma.IntFieldUpdateOperationsInput | number
  newsletter?: Prisma.NewsletterUpdateOneRequiredWithoutLinksNestedInput
}

export type NewsletterLinkUncheckedUpdateWithoutLinkInput = {
  newsletterId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type NewsletterLinkUncheckedUpdateManyWithoutLinkInput = {
  newsletterId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type NewsletterLinkCreateManyNewsletterInput = {
  linkId: string
  position?: number
}

export type NewsletterLinkUpdateWithoutNewsletterInput = {
  position?: Prisma.IntFieldUpdateOperationsInput | number
  link?: Prisma.LinkUpdateOneRequiredWithoutNewslettersNestedInput
}

export type NewsletterLinkUncheckedUpdateWithoutNewsletterInput = {
  linkId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type NewsletterLinkUncheckedUpdateManyWithoutNewsletterInput = {
  linkId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
}



export type NewsletterLinkSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  newsletterId?: boolean
  linkId?: boolean
  position?: boolean
  newsletter?: boolean | Prisma.NewsletterDefaultArgs<ExtArgs>
  link?: boolean | Prisma.LinkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["newsletterLink"]>

export type NewsletterLinkSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  newsletterId?: boolean
  linkId?: boolean
  position?: boolean
  newsletter?: boolean | Prisma.NewsletterDefaultArgs<ExtArgs>
  link?: boolean | Prisma.LinkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["newsletterLink"]>

export type NewsletterLinkSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  newsletterId?: boolean
  linkId?: boolean
  position?: boolean
  newsletter?: boolean | Prisma.NewsletterDefaultArgs<ExtArgs>
  link?: boolean | Prisma.LinkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["newsletterLink"]>

export type NewsletterLinkSelectScalar = {
  newsletterId?: boolean
  linkId?: boolean
  position?: boolean
}

export type NewsletterLinkOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"newsletterId" | "linkId" | "position", ExtArgs["result"]["newsletterLink"]>
export type NewsletterLinkInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  newsletter?: boolean | Prisma.NewsletterDefaultArgs<ExtArgs>
  link?: boolean | Prisma.LinkDefaultArgs<ExtArgs>
}
export type NewsletterLinkIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  newsletter?: boolean | Prisma.NewsletterDefaultArgs<ExtArgs>
  link?: boolean | Prisma.LinkDefaultArgs<ExtArgs>
}
export type NewsletterLinkIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  newsletter?: boolean | Prisma.NewsletterDefaultArgs<ExtArgs>
  link?: boolean | Prisma.LinkDefaultArgs<ExtArgs>
}

export type $NewsletterLinkPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "NewsletterLink"
  objects: {
    newsletter: Prisma.$NewsletterPayload<ExtArgs>
    link: Prisma.$LinkPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    newsletterId: string
    linkId: string
    position: number
  }, ExtArgs["result"]["newsletterLink"]>
  composites: {}
}

export type NewsletterLinkGetPayload<S extends boolean | null | undefined | NewsletterLinkDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NewsletterLinkPayload, S>

export type NewsletterLinkCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NewsletterLinkFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NewsletterLinkCountAggregateInputType | true
  }

export interface NewsletterLinkDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['NewsletterLink'], meta: { name: 'NewsletterLink' } }
  /**
   * Find zero or one NewsletterLink that matches the filter.
   * @param {NewsletterLinkFindUniqueArgs} args - Arguments to find a NewsletterLink
   * @example
   * // Get one NewsletterLink
   * const newsletterLink = await prisma.newsletterLink.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NewsletterLinkFindUniqueArgs>(args: Prisma.SelectSubset<T, NewsletterLinkFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NewsletterLinkClient<runtime.Types.Result.GetResult<Prisma.$NewsletterLinkPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one NewsletterLink that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NewsletterLinkFindUniqueOrThrowArgs} args - Arguments to find a NewsletterLink
   * @example
   * // Get one NewsletterLink
   * const newsletterLink = await prisma.newsletterLink.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NewsletterLinkFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NewsletterLinkFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NewsletterLinkClient<runtime.Types.Result.GetResult<Prisma.$NewsletterLinkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NewsletterLink that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsletterLinkFindFirstArgs} args - Arguments to find a NewsletterLink
   * @example
   * // Get one NewsletterLink
   * const newsletterLink = await prisma.newsletterLink.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NewsletterLinkFindFirstArgs>(args?: Prisma.SelectSubset<T, NewsletterLinkFindFirstArgs<ExtArgs>>): Prisma.Prisma__NewsletterLinkClient<runtime.Types.Result.GetResult<Prisma.$NewsletterLinkPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NewsletterLink that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsletterLinkFindFirstOrThrowArgs} args - Arguments to find a NewsletterLink
   * @example
   * // Get one NewsletterLink
   * const newsletterLink = await prisma.newsletterLink.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NewsletterLinkFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NewsletterLinkFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NewsletterLinkClient<runtime.Types.Result.GetResult<Prisma.$NewsletterLinkPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more NewsletterLinks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsletterLinkFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all NewsletterLinks
   * const newsletterLinks = await prisma.newsletterLink.findMany()
   * 
   * // Get first 10 NewsletterLinks
   * const newsletterLinks = await prisma.newsletterLink.findMany({ take: 10 })
   * 
   * // Only select the `newsletterId`
   * const newsletterLinkWithNewsletterIdOnly = await prisma.newsletterLink.findMany({ select: { newsletterId: true } })
   * 
   */
  findMany<T extends NewsletterLinkFindManyArgs>(args?: Prisma.SelectSubset<T, NewsletterLinkFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NewsletterLinkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a NewsletterLink.
   * @param {NewsletterLinkCreateArgs} args - Arguments to create a NewsletterLink.
   * @example
   * // Create one NewsletterLink
   * const NewsletterLink = await prisma.newsletterLink.create({
   *   data: {
   *     // ... data to create a NewsletterLink
   *   }
   * })
   * 
   */
  create<T extends NewsletterLinkCreateArgs>(args: Prisma.SelectSubset<T, NewsletterLinkCreateArgs<ExtArgs>>): Prisma.Prisma__NewsletterLinkClient<runtime.Types.Result.GetResult<Prisma.$NewsletterLinkPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many NewsletterLinks.
   * @param {NewsletterLinkCreateManyArgs} args - Arguments to create many NewsletterLinks.
   * @example
   * // Create many NewsletterLinks
   * const newsletterLink = await prisma.newsletterLink.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NewsletterLinkCreateManyArgs>(args?: Prisma.SelectSubset<T, NewsletterLinkCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many NewsletterLinks and returns the data saved in the database.
   * @param {NewsletterLinkCreateManyAndReturnArgs} args - Arguments to create many NewsletterLinks.
   * @example
   * // Create many NewsletterLinks
   * const newsletterLink = await prisma.newsletterLink.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many NewsletterLinks and only return the `newsletterId`
   * const newsletterLinkWithNewsletterIdOnly = await prisma.newsletterLink.createManyAndReturn({
   *   select: { newsletterId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends NewsletterLinkCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, NewsletterLinkCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NewsletterLinkPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a NewsletterLink.
   * @param {NewsletterLinkDeleteArgs} args - Arguments to delete one NewsletterLink.
   * @example
   * // Delete one NewsletterLink
   * const NewsletterLink = await prisma.newsletterLink.delete({
   *   where: {
   *     // ... filter to delete one NewsletterLink
   *   }
   * })
   * 
   */
  delete<T extends NewsletterLinkDeleteArgs>(args: Prisma.SelectSubset<T, NewsletterLinkDeleteArgs<ExtArgs>>): Prisma.Prisma__NewsletterLinkClient<runtime.Types.Result.GetResult<Prisma.$NewsletterLinkPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one NewsletterLink.
   * @param {NewsletterLinkUpdateArgs} args - Arguments to update one NewsletterLink.
   * @example
   * // Update one NewsletterLink
   * const newsletterLink = await prisma.newsletterLink.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NewsletterLinkUpdateArgs>(args: Prisma.SelectSubset<T, NewsletterLinkUpdateArgs<ExtArgs>>): Prisma.Prisma__NewsletterLinkClient<runtime.Types.Result.GetResult<Prisma.$NewsletterLinkPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more NewsletterLinks.
   * @param {NewsletterLinkDeleteManyArgs} args - Arguments to filter NewsletterLinks to delete.
   * @example
   * // Delete a few NewsletterLinks
   * const { count } = await prisma.newsletterLink.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NewsletterLinkDeleteManyArgs>(args?: Prisma.SelectSubset<T, NewsletterLinkDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NewsletterLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsletterLinkUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many NewsletterLinks
   * const newsletterLink = await prisma.newsletterLink.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NewsletterLinkUpdateManyArgs>(args: Prisma.SelectSubset<T, NewsletterLinkUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NewsletterLinks and returns the data updated in the database.
   * @param {NewsletterLinkUpdateManyAndReturnArgs} args - Arguments to update many NewsletterLinks.
   * @example
   * // Update many NewsletterLinks
   * const newsletterLink = await prisma.newsletterLink.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more NewsletterLinks and only return the `newsletterId`
   * const newsletterLinkWithNewsletterIdOnly = await prisma.newsletterLink.updateManyAndReturn({
   *   select: { newsletterId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends NewsletterLinkUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, NewsletterLinkUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NewsletterLinkPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one NewsletterLink.
   * @param {NewsletterLinkUpsertArgs} args - Arguments to update or create a NewsletterLink.
   * @example
   * // Update or create a NewsletterLink
   * const newsletterLink = await prisma.newsletterLink.upsert({
   *   create: {
   *     // ... data to create a NewsletterLink
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the NewsletterLink we want to update
   *   }
   * })
   */
  upsert<T extends NewsletterLinkUpsertArgs>(args: Prisma.SelectSubset<T, NewsletterLinkUpsertArgs<ExtArgs>>): Prisma.Prisma__NewsletterLinkClient<runtime.Types.Result.GetResult<Prisma.$NewsletterLinkPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of NewsletterLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsletterLinkCountArgs} args - Arguments to filter NewsletterLinks to count.
   * @example
   * // Count the number of NewsletterLinks
   * const count = await prisma.newsletterLink.count({
   *   where: {
   *     // ... the filter for the NewsletterLinks we want to count
   *   }
   * })
  **/
  count<T extends NewsletterLinkCountArgs>(
    args?: Prisma.Subset<T, NewsletterLinkCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NewsletterLinkCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a NewsletterLink.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsletterLinkAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NewsletterLinkAggregateArgs>(args: Prisma.Subset<T, NewsletterLinkAggregateArgs>): Prisma.PrismaPromise<GetNewsletterLinkAggregateType<T>>

  /**
   * Group by NewsletterLink.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsletterLinkGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NewsletterLinkGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NewsletterLinkGroupByArgs['orderBy'] }
      : { orderBy?: NewsletterLinkGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NewsletterLinkGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNewsletterLinkGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the NewsletterLink model
 */
readonly fields: NewsletterLinkFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for NewsletterLink.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NewsletterLinkClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  newsletter<T extends Prisma.NewsletterDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.NewsletterDefaultArgs<ExtArgs>>): Prisma.Prisma__NewsletterClient<runtime.Types.Result.GetResult<Prisma.$NewsletterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  link<T extends Prisma.LinkDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LinkDefaultArgs<ExtArgs>>): Prisma.Prisma__LinkClient<runtime.Types.Result.GetResult<Prisma.$LinkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the NewsletterLink model
 */
export interface NewsletterLinkFieldRefs {
  readonly newsletterId: Prisma.FieldRef<"NewsletterLink", 'String'>
  readonly linkId: Prisma.FieldRef<"NewsletterLink", 'String'>
  readonly position: Prisma.FieldRef<"NewsletterLink", 'Int'>
}
    

// Custom InputTypes
/**
 * NewsletterLink findUnique
 */
export type NewsletterLinkFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterLink
   */
  select?: Prisma.NewsletterLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterLink
   */
  omit?: Prisma.NewsletterLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterLinkInclude<ExtArgs> | null
  /**
   * Filter, which NewsletterLink to fetch.
   */
  where: Prisma.NewsletterLinkWhereUniqueInput
}

/**
 * NewsletterLink findUniqueOrThrow
 */
export type NewsletterLinkFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterLink
   */
  select?: Prisma.NewsletterLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterLink
   */
  omit?: Prisma.NewsletterLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterLinkInclude<ExtArgs> | null
  /**
   * Filter, which NewsletterLink to fetch.
   */
  where: Prisma.NewsletterLinkWhereUniqueInput
}

/**
 * NewsletterLink findFirst
 */
export type NewsletterLinkFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterLink
   */
  select?: Prisma.NewsletterLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterLink
   */
  omit?: Prisma.NewsletterLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterLinkInclude<ExtArgs> | null
  /**
   * Filter, which NewsletterLink to fetch.
   */
  where?: Prisma.NewsletterLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewsletterLinks to fetch.
   */
  orderBy?: Prisma.NewsletterLinkOrderByWithRelationInput | Prisma.NewsletterLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NewsletterLinks.
   */
  cursor?: Prisma.NewsletterLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewsletterLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewsletterLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NewsletterLinks.
   */
  distinct?: Prisma.NewsletterLinkScalarFieldEnum | Prisma.NewsletterLinkScalarFieldEnum[]
}

/**
 * NewsletterLink findFirstOrThrow
 */
export type NewsletterLinkFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterLink
   */
  select?: Prisma.NewsletterLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterLink
   */
  omit?: Prisma.NewsletterLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterLinkInclude<ExtArgs> | null
  /**
   * Filter, which NewsletterLink to fetch.
   */
  where?: Prisma.NewsletterLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewsletterLinks to fetch.
   */
  orderBy?: Prisma.NewsletterLinkOrderByWithRelationInput | Prisma.NewsletterLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NewsletterLinks.
   */
  cursor?: Prisma.NewsletterLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewsletterLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewsletterLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NewsletterLinks.
   */
  distinct?: Prisma.NewsletterLinkScalarFieldEnum | Prisma.NewsletterLinkScalarFieldEnum[]
}

/**
 * NewsletterLink findMany
 */
export type NewsletterLinkFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterLink
   */
  select?: Prisma.NewsletterLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterLink
   */
  omit?: Prisma.NewsletterLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterLinkInclude<ExtArgs> | null
  /**
   * Filter, which NewsletterLinks to fetch.
   */
  where?: Prisma.NewsletterLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewsletterLinks to fetch.
   */
  orderBy?: Prisma.NewsletterLinkOrderByWithRelationInput | Prisma.NewsletterLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing NewsletterLinks.
   */
  cursor?: Prisma.NewsletterLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewsletterLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewsletterLinks.
   */
  skip?: number
  distinct?: Prisma.NewsletterLinkScalarFieldEnum | Prisma.NewsletterLinkScalarFieldEnum[]
}

/**
 * NewsletterLink create
 */
export type NewsletterLinkCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterLink
   */
  select?: Prisma.NewsletterLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterLink
   */
  omit?: Prisma.NewsletterLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterLinkInclude<ExtArgs> | null
  /**
   * The data needed to create a NewsletterLink.
   */
  data: Prisma.XOR<Prisma.NewsletterLinkCreateInput, Prisma.NewsletterLinkUncheckedCreateInput>
}

/**
 * NewsletterLink createMany
 */
export type NewsletterLinkCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many NewsletterLinks.
   */
  data: Prisma.NewsletterLinkCreateManyInput | Prisma.NewsletterLinkCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * NewsletterLink createManyAndReturn
 */
export type NewsletterLinkCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterLink
   */
  select?: Prisma.NewsletterLinkSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterLink
   */
  omit?: Prisma.NewsletterLinkOmit<ExtArgs> | null
  /**
   * The data used to create many NewsletterLinks.
   */
  data: Prisma.NewsletterLinkCreateManyInput | Prisma.NewsletterLinkCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterLinkIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * NewsletterLink update
 */
export type NewsletterLinkUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterLink
   */
  select?: Prisma.NewsletterLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterLink
   */
  omit?: Prisma.NewsletterLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterLinkInclude<ExtArgs> | null
  /**
   * The data needed to update a NewsletterLink.
   */
  data: Prisma.XOR<Prisma.NewsletterLinkUpdateInput, Prisma.NewsletterLinkUncheckedUpdateInput>
  /**
   * Choose, which NewsletterLink to update.
   */
  where: Prisma.NewsletterLinkWhereUniqueInput
}

/**
 * NewsletterLink updateMany
 */
export type NewsletterLinkUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update NewsletterLinks.
   */
  data: Prisma.XOR<Prisma.NewsletterLinkUpdateManyMutationInput, Prisma.NewsletterLinkUncheckedUpdateManyInput>
  /**
   * Filter which NewsletterLinks to update
   */
  where?: Prisma.NewsletterLinkWhereInput
  /**
   * Limit how many NewsletterLinks to update.
   */
  limit?: number
}

/**
 * NewsletterLink updateManyAndReturn
 */
export type NewsletterLinkUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterLink
   */
  select?: Prisma.NewsletterLinkSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterLink
   */
  omit?: Prisma.NewsletterLinkOmit<ExtArgs> | null
  /**
   * The data used to update NewsletterLinks.
   */
  data: Prisma.XOR<Prisma.NewsletterLinkUpdateManyMutationInput, Prisma.NewsletterLinkUncheckedUpdateManyInput>
  /**
   * Filter which NewsletterLinks to update
   */
  where?: Prisma.NewsletterLinkWhereInput
  /**
   * Limit how many NewsletterLinks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterLinkIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * NewsletterLink upsert
 */
export type NewsletterLinkUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterLink
   */
  select?: Prisma.NewsletterLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterLink
   */
  omit?: Prisma.NewsletterLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterLinkInclude<ExtArgs> | null
  /**
   * The filter to search for the NewsletterLink to update in case it exists.
   */
  where: Prisma.NewsletterLinkWhereUniqueInput
  /**
   * In case the NewsletterLink found by the `where` argument doesn't exist, create a new NewsletterLink with this data.
   */
  create: Prisma.XOR<Prisma.NewsletterLinkCreateInput, Prisma.NewsletterLinkUncheckedCreateInput>
  /**
   * In case the NewsletterLink was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NewsletterLinkUpdateInput, Prisma.NewsletterLinkUncheckedUpdateInput>
}

/**
 * NewsletterLink delete
 */
export type NewsletterLinkDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterLink
   */
  select?: Prisma.NewsletterLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterLink
   */
  omit?: Prisma.NewsletterLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterLinkInclude<ExtArgs> | null
  /**
   * Filter which NewsletterLink to delete.
   */
  where: Prisma.NewsletterLinkWhereUniqueInput
}

/**
 * NewsletterLink deleteMany
 */
export type NewsletterLinkDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NewsletterLinks to delete
   */
  where?: Prisma.NewsletterLinkWhereInput
  /**
   * Limit how many NewsletterLinks to delete.
   */
  limit?: number
}

/**
 * NewsletterLink without action
 */
export type NewsletterLinkDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsletterLink
   */
  select?: Prisma.NewsletterLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsletterLink
   */
  omit?: Prisma.NewsletterLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsletterLinkInclude<ExtArgs> | null
}
