export const AVAILABLE_TAGS = [
    "Svelte",
    "Next.js",
    "Astro",
    "Remix",
    "React",
    "Web Components",
    "CSS",
    "Tailwind",
    "Design Systems",
    "Component Libraries",
    "UI/UX",
    "Accessibility",
    "Figma",
    "(Framer) Motion",
    "GSAP",
    "Animation",
    "3D",
    "Tooling",
    "JavaScript / TypeScript",
    "Web Performance",
    "Libraries",
    "AI & ML",
    "CMS",
    "Testing",
    "Storybook",
    "Infrastructure",
    "Vercel AI SDK",
    "Vercel Workflow DevKit",
    "Baseline",
] as const;

export type AvailableTag = (typeof AVAILABLE_TAGS)[number];
